---
title: "R Notebook"
output: html_notebook
---

# import data

```{r}
source("./scripts/icd.R")
### attendance records from stata file
stata = mclapply(list("AE_Attendance_transformed_20150101_20210917.csv"), import_csv, mc.cores=40)

stata = stata %>%
  mutate(year = lubridate::year(eventdate),
         eventdate = as.Date(eventdate)) %>% 
  filter(eventdate<max(eventdate)-28,
         year != 2015)

### comorbidities
# comorbidities_quan_deyo <- stata %>%
#           select(year, eventdate, AENumber, ReferenceKey, death, paste0("DR", 1:10)) %>%
#           icd::icd9_comorbid(map = icd::icd9_map_quan_deyo, visit_name = "AENumber", icd_name = paste0("DR", 1:10)) %>%
#           mutate(NoneMapped = (rowSums(across(-c(AENumber, death, NoCode))) == 0 & !NoCode))
comorbidities_quan_deyo <- stata %>% 
          select(AENumber, ReferenceKey, death, paste0("DR", 1:10)) %>%
          get_dx_comorbidities(icd9map = icd::icd9_map_quan_deyo)
```


# fig 5 

```{r}
# get wave 5 aka 2021 wave 4 dates
wave.dates <- import_waves() %>% 
  filter(year == 2021) %>%
  import_dates() %>%
  filter(wave_num %in% c(5),
         year==2021) %>%
  mutate(date = yday(date)) %>%
  pull(date)

# # set filters in strings
# title.filter <- tribble(
#         ~ title,
#         ~ filter,
#         "Wave periods; 65+",
#         "eventdate %in% wave.dates & age >= 65",
#         "Non-wave periods; 65+",
#         "!eventdate %in% wave.dates & age >= 65"
# )

df <- stata %>% 
  # drop DOA and filter 65+ only
        filter(doadba != 1,
               age>=65) %>%
  mutate(demographic = ifelse(yday(eventdate) %in% wave.dates, "2021 Wave", "2021 Non-wave")) 
### Tabulate changes routine for each filtered dataframe

tabulate_changes <- function(df, comorbidity = NULL, conditions_to_add = NULL, group.by = c("demographic")) {
  #' tabulate 2020 vs 2016-2019 changes of comorbidity attendance and deaths (2021 vs 2016-2019 to be added)
  #' 
  #'
  #' @param df The original dataframe
  #' @param comorbidity A dataframe that contains icd9 comorbidities
  #' @param conditions_to_add additional icd9 categories to add
  #' @return dataframe of changes of all icd9 categories
        
          if (is.null(conditions_to_add)) conditions_to_add <- c()
          
          # input args:
          # df <- stata %>% 
          #     # drop DOA and filter 65+ only
          #           filter(doadba != 1,
          #                  age>=65,
          #                  year < 2021) %>%
          #     mutate(demographic = ifelse(yday(eventdate) %in% wave.dates, "2020 Wave", "2020 Non-wave"))
          # comorbidity = comorbidities_quan_deyo
          # conditions_to_add = c()
          
          # original set of conditions
          con.names.orig <- names(icd::icd9_map_quan_deyo)
          con.names.orig = con.names.orig[!(con.names.orig %in% "HIV")]
          # set of all conditions
          con.names.all <- c(con.names.orig, conditions_to_add, "NoneMapped")
          # set of other conditions
          con.names.others <- con.names.all[str_detect(con.names.all, "NoneMapped", negate = T)]
          
          AE_whitelist <- pull(df, AENumber)
          
          # icd_conditions = comorbidity %>% select(-AENumber) %>% colnames()
                
          comorb.filtered <- comorbidity %>% 
                  # select AENumber and comorbidity columns only 
                  # (to ensure reproducibility)
                  select(AENumber, all_of(con.names.orig)) %>% 
                  # filter AENumber from user-supplied dataframe (for subsetting)
                  filter(AENumber %in% AE_whitelist) %>% 
                  # add back pneumonia and death information
                  left_join(df %>% select(AENumber, year, death, all_of(conditions_to_add), eventdate, !!!syms(group.by)),
                            by = "AENumber") %>%
                  mutate(year = as.character(year)) %>%
                  # compute NoneMapped
                  mutate(NoneMapped = (rowSums(across(all_of(con.names.others))) == 0),
                         yday = yday(eventdate))
          # browser()
         
          # yearly comparison with non-covid yrs
          # loop over icd conditions
          out.changes = c()
          
          for(icd_cond in con.names.others){
            # browser()
            print(paste0("calculating changes of icd category: ", icd_cond))
            # change
            results <- compare_yearly(comorb.filtered, 
                                      group.by = c(group.by, icd_cond), 
                                      trtyrs = c(2021),
                                      dates.2021 = dates.2021
                                      )
            out.changes.placeholder = results[[2]] %>% 
              filter(!!!syms(icd_cond)) %>% 
              mutate(condition = icd_cond) %>%
              select(-one_of(icd_cond)) 
            # browser()
            out.changes = bind_rows(out.changes, out.changes.placeholder)
          }
          
          return(out.changes)
        
}


annotation.df <- tribble(
        ~label, ~condition,
        "MI","MI",
        "CHF","CHF",
        "PVD","PVD",
        "Stroke","Stroke",
        "Dementia","Dementia",
        "Chronic pulm. disease","Pulmonary",
        "Rheumatic disease","Rheumatic",
        "PUD","PUD",
        "Mild liver disease","LiverMild",
        "DM w/o chronic complications","DM",
        "DM w/ chronic complications","DMcx",
        "Hemiplegia/paraplegia","Paralysis",
        "Renal disease","Renal",
        "Cancer","Cancer",
        "Moderate/severe liver disease","LiverSevere",
        "Metastatic solid tumour","Mets",
        "AIDS/HIV","HIV",
        "Missing code","NoCode",
        "Others","NoneMapped",
        "death","death",
        # "Pneumonia","pneu",
        "Sepsis","diag"
)

results = tabulate_changes(df, comorbidities_quan_deyo, group.by = c("demographic"))
tableDeyo = results %>%
  filter(ctrltrt == "ctrl")

```



```{r}
### Plotting

size_breaks = c(50,100,500,1000,5000)
deaths_per_year = 10
ncol = 2
text_size = 1.75

group.by = c("demographic")
plotready = tableDeyo %>%
    filter(abs(n) > deaths_per_year) %>%
    group_by(year, condition, !!!syms(group.by)) %>%
    mutate(x = percent_diff[death==-1]) %>%
    filter(death == 1) %>%
    select(-death, -ctrltrt) %>%
    rename(y = percent_diff,
           diff_1 = abs_diff) %>%
  # textual label for plotting
    mutate(label = paste0(condition, " (", sprintf("%+d", diff_1), ")"))

xlim <- c(min(plotready$x), max(plotready$x))
ylim <- c(min(plotready$y), max(plotready$y))

fig5.raw <- (
  plotready %>% 
               ### Plotting
               ggplot(aes(x = x, y = y, col = diff_1, label = `label`)) +
               ### reference lines
               geom_hline(yintercept = 0, col = "lightgrey") +
               geom_vline(xintercept = 0, col = "lightgrey") +
               geom_abline(intercept = 0, slope = 1, col = "steelblue") +
               ### datapoints
               geom_point(aes(size = n), alpha = 0.3) +
               geom_text_repel(size = text_size, force = 10, max.overlaps = 20) +
               ### annotations
               labs(
                       x = "Episode Admission Seasonally-Adjusted Change (%)",
                       y = "28-day All-Cause Mortality\nSeasonally-Adjusted Change (%)",
                       size = "Deaths"
               ) +
               ### colours 
               scale_colour_gradient2(low = "blue", mid = "dark grey", high = "red",
                                        limits = c(-100, 100),
                                        oob = scales::squish,
                                        name = "Year-on-year\ndifference\nin deaths")+ 
               ### point size
               scale_size_continuous(breaks = size_breaks)+ 
               ### facets
               facet_wrap(~demographic, ncol = ncol,
                            scales = "free", drop = FALSE
                            # here scales is set to "free" to show the axis in each facet
                            # as long as limits are provided, then ok
               ) +
               ### scales
               scale_x_continuous(limits = xlim,
                                    expand = expansion(mult = c(0.05, 0.05))
               ) + 
               scale_y_continuous(limits = ylim,
                                    expand = expansion(mult = c(0.05, 0.05))
               )+ 
               ## themes 
               theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                       panel.background = element_blank(), axis.line = element_line(colour = "black")) + 
               theme(legend.position = "bottom")
        )

fig5.raw
        
# aesthetics / themes
fig5 <- ( fig5.raw
  + guides(shape = guide_legend(override.aes = list(size = 6), order = 1))
  
  + theme(text = element_text(size = 8),
          legend.title = element_text(size = 6), 
        legend.text = element_text(size = 6),
        legend.position = "bottom",
                    
  )
  + facet_wrap(~demographic, ncol = 2, scales = "free", drop = T) 
  
)

fig5 
ggsave(plot=fig5, file=file.path(out_dir, "figS3.svg"), height = 4, width = 8.3 - 0.75*2)

invisible(dev.off())
gc()
```

