---
title: "R Notebook"
output: html_notebook
---

```{r}


# stata %>% 
#   filter(age >= 65, if_any(DR1:DR10,~grepl("E95",.))) %>% 
#   count(year, death) %>%
#   filter(death == 1)

df = stata %>% 
  filter() %>%
  select(AENumber, eventdate, age, paste0("DR", 1:10)) 

df_imputed = df %>% 
  # head() %>%
  mutate(
    # "f001_139" = ifelse(if_any(DR1:DR10,~between(.,'001', '139')), 1, 0),
    # "f140_239" = ifelse(if_any(DR1:DR10,~between(.,'140', '239')), 1, 0),
    # "f240_279" = ifelse(if_any(DR1:DR10,~between(.,'240', '279')), 1, 0),
    # "f280_289" = ifelse(if_any(DR1:DR10,~between(.,'280', '289')), 1, 0),
    "f290_319" = ifelse(if_any(DR1:DR10,~between(.,'290', '319')), 1, 0),
    # "f320_389" = ifelse(if_any(DR1:DR10,~between(.,'320', '389')), 1, 0),
    # "f390_459" = ifelse(if_any(DR1:DR10,~between(.,'390', '459')), 1, 0),
    # "f460_519" = ifelse(if_any(DR1:DR10,~between(.,'460', '519')), 1, 0),
    # "f520_579" = ifelse(if_any(DR1:DR10,~between(.,'520', '579')), 1, 0),
    # "f580_629" = ifelse(if_any(DR1:DR10,~between(.,'580', '629')), 1, 0),
    # "f630_679" = ifelse(if_any(DR1:DR10,~between(.,'630', '679')), 1, 0),
    # "f680_709" = ifelse(if_any(DR1:DR10,~between(.,'680', '709')), 1, 0),
    # "f710_739" = ifelse(if_any(DR1:DR10,~between(.,'710', '739')), 1, 0),
    # "f740_759" = ifelse(if_any(DR1:DR10,~between(.,'740', '759')), 1, 0),
    # "f760_779" = ifelse(if_any(DR1:DR10,~between(.,'760', '779')), 1, 0),
    # "f780_799" = ifelse(if_any(DR1:DR10,~between(.,'780', '799')), 1, 0),
    # "f800_999" = ifelse(if_any(DR1:DR10,~between(.,'800', '999')), 1, 0),
    # "V01_V91" = ifelse(if_any(DR1:DR10,~grepl("V",.)), 1, 0),
    # "E000_E999" = ifelse(if_any(DR1:DR10,~grepl("E",.)), 1, 0),
    "E950_E959" = ifelse(if_any(DR1:DR10,~grepl("E95",.)), 1, 0),
    # NoCode = ifelse(if_any(DR1:DR10, ~!is.na(.)), 0, 1)
  ) %>%
  select(-paste0("DR", 1:10))

cols = df_imputed %>% 
  select(-AENumber, -eventdate, -age) %>%
  colnames() 
df_counts = as_tibble(c())
for(col in cols){
  df_counts = rbind(df_counts,
  df_imputed %>%
    count(eval(parse(text = paste0(col,'==1'))), eventdate) %>%
    filter_at(1, ~. == T) %>%
    mutate(group = col) %>%
    select_at(-1)
  )
}
df_counts = rbind(df_counts,
  df_imputed %>%
    count(E950_E959 == 1 & f290_319 == 1, eventdate) %>%
    filter_at(1, ~. == T) %>%
    mutate(group = "E950_E959 intersect f290_319") %>%
    select_at(-1)
  )
# df_counts = df_counts %>%
#   pivot_wider(
#     names_from = year,
#     values_from = n
#   )
p1 = ggplot() + 
  geom_line(data = filter(df_counts, group == "E950_E959", year(eventdate) >= 2019), aes(x = eventdate, y = n)) +
  ggtitle("suicide")
library(zoo)
ggplot() + 
  geom_line(data = filter(df_counts, group == "E950_E959", year(eventdate) >= 2020), aes(x = eventdate, y = zoo::rollmean(n, 7, na.pad = T, align = "right"), col=group)) +
  geom_line(data = filter(df_counts, group == "f290_319", year(eventdate) >= 2020), aes(x = eventdate, y = zoo::rollmean(n / 10, 7, na.pad = T, align = "right"), col=group)) +
  geom_line(data = filter(df_counts, group == "E950_E959 intersect f290_319", year(eventdate) >= 2020), aes(x = eventdate, y = zoo::rollmean(n, 7, na.pad = T, align = "right"), col=group)) +
  scale_y_continuous(
    
    # Features of the first axis
    name = "Suicide",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*10, name="Mental Disorder")
  )

```


```{r}
# writexl::write_xlsx(df_counts, path = here("65plus_suicide_byyr.xlsx"))

```

